"""'InitialMigration'

Revision ID: 89373f106969
Revises: 
Create Date: 2023-09-08 10:58:41.000251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89373f106969'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_color', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favourite_color')

    # ### end Alembic commands ###
